import * as fs from 'fs';
import * as path from 'path';
import { LunitConfig } from './config';

/**
 * Unlike everything else this extension generates (compiled runner scripts,
 * the Studio test project, the bootstrap script, ...), this file is meant to
 * be committed to the project and read by coding agents (Claude Code, or any
 * other tool that scans AGENTS.md) -- so, deliberately, it's the one thing
 * this extension writes *into* the workspace rather than into VS Code's own
 * storage. Still opt-in only (see `lunit.installAgentInstructions`), never
 * written automatically.
 */
const BEGIN_MARKER = '<!-- BEGIN lunit-test-explorer:agent-instructions -->';
const END_MARKER = '<!-- END lunit-test-explorer:agent-instructions -->';

function buildSection(config: LunitConfig): string {
	return `${BEGIN_MARKER}
<!-- Auto-generated by the "Lunit: Add/Update Agent Instructions" VS Code command.
     Re-running it replaces only the text between these markers, so anything
     you add outside them is preserved. -->

## Testing (\`@rbxts/lunit\`, via the "Lunit Test Explorer" VS Code extension)

This project's tests are written with **@rbxts/lunit** (a class + decorator
based test framework) and are discovered/run through the **Lunit Test
Explorer** VS Code extension's Test Explorer integration -- not a script you
invoke yourself. See "Verifying your work" below before trying to run them.

### Where tests live

Test source files match the glob \`${config.testGlob}\` (relative to the
workspace folder), excluding \`${config.excludeGlob}\`. A file is usually one
test class.

### How a test file is structured

\`\`\`ts
import { Test, Assert } from "@rbxts/lunit";

class MyFeature {
	@Test
	public doesTheThing() {
		Assert.equal(1 + 1, 2);
	}
}

export = MyFeature;
\`\`\`

- The class must be the module's sole export via \`export = ClassName\`, not a
  named \`export class\` -- the test runner requires the compiled module and
  expects it to evaluate directly to the class.
- \`@Test\` marks a method as a test case (with or without \`()\`).
- Other \`@rbxts/lunit\` decorators, usable at class or method level:
  \`@DisplayName("...")\`, \`@Skip(condition, "reason")\`, \`@Only\`,
  \`@Each([[...], [...]])\` (one independent result per row), \`@Retry(n)\`,
  \`@Repeat(n)\`, \`@Timeout(ms)\`, \`@Order(n)\`, \`@Disabled("reason")\`,
  \`@Negated\`, and the lifecycle hooks \`@Before\`/\`@BeforeEach\`/\`@BeforeAll\`,
  \`@After\`/\`@AfterEach\`/\`@AfterAll\`.

### Running under Lune vs. Roblox Studio -- \`@Tag("Studio")\` / \`@Tag("Lune")\`

This extension runs tests two ways: a fast, headless **"Run with Lune"**
profile, and a **"Run in Roblox Studio"** profile for tests that need real
Roblox APIs.

Tag a test \`@Tag("Studio")\` (class or method level) if it touches \`game\`,
mounts a \`@rbxts/react\`/\`@rbxts/react-roblox\` component, creates real
\`Instance\`s, or otherwise needs actual Roblox Studio to run -- it will then
be skipped entirely under "Run with Lune" (never attempted, never shown as a
failure there). Tag \`@Tag("Lune")\` for the rare test that should *only* run
under Lune, excluding it from "Run in Roblox Studio". An untagged test runs
under both. Don't leave a Studio-only test untagged expecting it to "skip
gracefully" under Lune -- tag it, or it will either fail to load or (worse)
partially execute against APIs that don't exist there.

\`\`\`ts
import { Test, Tag } from "@rbxts/lunit";

@Tag("Studio")
class MountsAComponent {
	@Test
	public rendersWithoutErrors() {
		// uses game / Instance.new / React mounting -- Studio only
	}
}

export = MountsAComponent;
\`\`\`

### Verifying your work

Don't compile and invoke Lunit's runner yourself from a terminal -- the
working test runner is regenerated fresh by this extension into VS Code's
own extension storage (outside the project) before every run, and
hand-invoking Lunit's own bundled scripts directly is known not to work with
roblox-ts's module resolution. Ask the user to run the tests from VS Code's
Test Explorer (or the "Lunit: Run All Tests" command), and read the results
there or in the "Lunit" output channel.
${END_MARKER}`;
}

/**
 * Creates (or, if one already exists, merges into) AGENTS.md at the
 * workspace root -- replacing only the marked section in place on repeat
 * runs so config changes (e.g. a custom testGlob) stay accurate without
 * clobbering anything the user added around it.
 */
export function installAgentInstructions(config: LunitConfig): { filePath: string; updated: boolean } {
	const filePath = path.join(config.workspaceFolder.uri.fsPath, 'AGENTS.md');
	const section = buildSection(config);

	if (!fs.existsSync(filePath)) {
		fs.writeFileSync(filePath, section + '\n', 'utf8');
		return { filePath, updated: false };
	}

	const existing = fs.readFileSync(filePath, 'utf8');
	const beginIdx = existing.indexOf(BEGIN_MARKER);
	const endIdx = existing.indexOf(END_MARKER);
	if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
		const before = existing.slice(0, beginIdx);
		const after = existing.slice(endIdx + END_MARKER.length);
		fs.writeFileSync(filePath, before + section + after, 'utf8');
	} else {
		const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
		fs.writeFileSync(filePath, existing + separator + section + '\n', 'utf8');
	}
	return { filePath, updated: true };
}
