import * as fs from 'fs';
import * as path from 'path';
import { LunitConfig } from './config';

/**
 * Unlike everything else this extension generates (compiled runner scripts,
 * the Studio test project, the bootstrap script, ...), this file is meant to
 * be committed to the project and read by coding agents (Claude Code, or any
 * other tool that scans AGENTS.md) -- so, deliberately, it's the one thing
 * this extension writes *into* the workspace rather than into VS Code's own
 * storage. Still opt-in only (see `lunit.installAgentInstructions`), never
 * written automatically.
 */
const BEGIN_MARKER = '<!-- BEGIN lunit-test-explorer:agent-instructions -->';
const END_MARKER = '<!-- END lunit-test-explorer:agent-instructions -->';

function buildSection(config: LunitConfig, cliLauncherPath: string | undefined): string {
	return `${BEGIN_MARKER}
<!-- Auto-generated by the "Lunit: Add/Update Agent Instructions" VS Code command.
     Re-running it replaces only the text between these markers, so anything
     you add outside them is preserved. -->

## Testing (\`@rbxts/lunit\`, via the "Lunit Test Explorer" VS Code extension)

This project's tests are written with **@rbxts/lunit** (a class + decorator
based test framework) and are discovered/run through the **Lunit Test
Explorer** VS Code extension's Test Explorer integration -- not a script you
invoke yourself. See "Verifying your work" below before trying to run them.

### Where tests live

Test source files match the glob \`${config.testGlob}\` (relative to the
workspace folder), excluding \`${config.excludeGlob}\`. A file is usually one
test class.

### How a test file is structured

\`\`\`ts
import { Test, Assert } from "@rbxts/lunit";

class MyFeature {
	@Test
	public doesTheThing() {
		Assert.equal(1 + 1, 2);
	}
}

export = MyFeature;
\`\`\`

- The class must be the module's sole export via \`export = ClassName\`, not a
  named \`export class\` -- the test runner requires the compiled module and
  expects it to evaluate directly to the class.
- \`@Test\` marks a method as a test case (with or without \`()\`).
- Other \`@rbxts/lunit\` decorators, usable at class or method level:
  \`@DisplayName("...")\`, \`@Skip(condition, "reason")\`, \`@Only\`,
  \`@Each([[...], [...]])\` (one independent result per row), \`@Retry(n)\`,
  \`@Repeat(n)\`, \`@Timeout(ms)\`, \`@Order(n)\`, \`@Disabled("reason")\`,
  \`@Negated\`, and the lifecycle hooks \`@Before\`/\`@BeforeEach\`/\`@BeforeAll\`,
  \`@After\`/\`@AfterEach\`/\`@AfterAll\`.

### Running under Lune vs. Roblox Studio -- \`@Tag("Studio")\` / \`@Tag("Lune")\`

This extension runs tests two ways: a fast, headless **"Run with Lune"**
profile, and a **"Run in Roblox Studio"** profile for tests that need real
Roblox APIs.

Tag a test \`@Tag("Studio")\` (class or method level) if it touches \`game\`,
mounts a \`@rbxts/react\`/\`@rbxts/react-roblox\` component, creates real
\`Instance\`s, or otherwise needs actual Roblox Studio to run -- it will then
be skipped entirely under "Run with Lune" (never attempted, never shown as a
failure there). Tag \`@Tag("Lune")\` for the rare test that should *only* run
under Lune, excluding it from "Run in Roblox Studio". An untagged test runs
under both. Don't leave a Studio-only test untagged expecting it to "skip
gracefully" under Lune -- tag it, or it will either fail to load or (worse)
partially execute against APIs that don't exist there.

\`\`\`ts
import { Test, Tag } from "@rbxts/lunit";

@Tag("Studio")
class MountsAComponent {
	@Test
	public rendersWithoutErrors() {
		// uses game / Instance.new / React mounting -- Studio only
	}
}

export = MountsAComponent;
\`\`\`

### Verifying your work: run the tests from the terminal

Don't compile and invoke Lunit's runner yourself -- the working test runner
is regenerated fresh by the extension before every run, and hand-invoking
Lunit's own bundled scripts directly is known not to work with roblox-ts's
module resolution. Instead, run the extension's own command-line entry point,
which executes the tests through the exact same code path as clicking "Run in
Roblox Studio" / "Run with Lune" in the Test Explorer and prints the same
per-test results (the run also shows up in the user's Testing view):

\`\`\`sh
${cliCommand(cliLauncherPath, '--studio')}
\`\`\`

- \`--studio\` (default) runs in Roblox Studio; \`--lune\` runs headlessly with
  Lune (Lune can't run \`@Tag("Studio")\` tests, so prefer \`--studio\` to
  verify everything at once).
- Tests tagged with one of the project's \`lunit.lune.slowTags\` (e.g.
  \`@Tag("Slow")\` long sweeps) are left out of \`--lune\` and \`--studio\`, and
  the summary says how many; add \`--full\` to run them too.
- Add one or more filters to run a subset, e.g. \`... --studio MyFeature\`
  or \`... --studio src/foo.test.ts\` -- case-insensitive substrings matched
  against each test's file path, class name, method name and display name.
- Add \`--json\` for a machine-readable summary on stdout (\`tests[]\` with
  \`status\`, \`message\`, \`file\`, \`className\`, \`methodName\`; \`counts\`).
- Exit code 0 means every test passed (or was skipped); 1 means at least one
  failed or errored (each is listed with its failure message); 2 means the run
  couldn't be performed at all -- read the printed reason, fix it if it's about
  your code, otherwise report it to the user.
- Studio runs can take a while (up to a few minutes if a new Studio process
  has to be launched); wait for the command to finish rather than assuming
  it hung. Use \`--help\` for every option.
${END_MARKER}`;
}

function cliCommand(cliLauncherPath: string | undefined, flags: string): string {
	if (!cliLauncherPath) {
		return `node "<path to the Lunit Test Companion extension>/out/cli.js" ${flags}`;
	}
	return `node "${cliLauncherPath}" ${flags}`;
}

/**
 * Creates (or, if one already exists, merges into) AGENTS.md at the
 * workspace root -- replacing only the marked section in place on repeat
 * runs so config changes (e.g. a custom testGlob) stay accurate without
 * clobbering anything the user added around it.
 */
export function installAgentInstructions(
	config: LunitConfig,
	cliLauncherPath: string | undefined,
): { filePath: string; updated: boolean } {
	const filePath = path.join(config.workspaceRoot, 'AGENTS.md');
	const section = buildSection(config, cliLauncherPath);

	if (!fs.existsSync(filePath)) {
		fs.writeFileSync(filePath, section + '\n', 'utf8');
		return { filePath, updated: false };
	}

	const existing = fs.readFileSync(filePath, 'utf8');
	const beginIdx = existing.indexOf(BEGIN_MARKER);
	const endIdx = existing.indexOf(END_MARKER);
	if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
		const before = existing.slice(0, beginIdx);
		const after = existing.slice(endIdx + END_MARKER.length);
		fs.writeFileSync(filePath, before + section + after, 'utf8');
	} else {
		const separator = existing.endsWith('\n\n') ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
		fs.writeFileSync(filePath, existing + separator + section + '\n', 'utf8');
	}
	return { filePath, updated: true };
}
