import { buildLuauEmitHelpers } from './luauEmitHelpers';
import { buildLuauTestFilterHelpers, SlowTestFilter, TestSelection } from './luauTestFilterTemplate';

/**
 * Builds the Roblox Studio bootstrap script for the "Run in Roblox Studio"
 * profile, run via Studio's `--task RunScript` CLI flag against the place
 * built from studioProjectTemplate.ts's generated Rojo project. Fully
 * generated and regenerated before every run -- nothing here is meant to be
 * hand-edited (there are no more per-project TODOs, unlike an earlier
 * version of this file: paths are now fully determined by the generated
 * Rojo project, not guessed).
 *
 * The one subtlety worth documenting: roblox-ts compiled modules start with
 * `local TS = _G[script]`, which is only populated by `TS.import`/
 * `TS.getModule` as a side effect of loading a module *through* them -- a
 * bare `require()` on a roblox-ts-compiled ModuleScript leaves `_G[script]`
 * nil and crashes on that very first line. So this script bootstraps the
 * chain by `require()`-ing only the one hand-written, non-compiled module
 * (`RuntimeLib`, shipped verbatim by roblox-ts) directly, then uses
 * `RuntimeLib.import`/`RuntimeLib.getModule` for everything else -- exactly
 * mirroring what compiled code itself does -- rather than calling `require()`
 * directly on Lunit or any test module.
 *
 * Test discovery searches the whole built place (`game:GetDescendants()`)
 * rather than just the package-under-test's own mount point: a project
 * embedded in a larger dev workspace can have its actual tests living under
 * an entirely different, independently-compiled nested package (see
 * studioRunner.ts's findNestedTestPackages) -- narrowing to one expected
 * location risks silently finding nothing. Mirrors
 * liveSyncScriptTemplate.ts's own broad walk, including the same "forks"
 * exclusion (react-lua ships its own forks/ReactFiberHostConfig.test.lua, a
 * false-positive name collision, not a real Lunit test). `rbxtsScope`
 * (node_modules["@rbxts"]) works as the import context for every discovered
 * module regardless of which package it actually belongs to -- `TS.import`/
 * `TS.getModule`'s ancestor walk just needs *a* node_modules two levels up
 * from wherever it starts, not specifically the module's own.
 *
 * Tests tagged @Tag("Lune") are left out (see luauTestFilterTemplate.ts), as
 * are slow tests (`slow`) the request did not name explicitly, and
 * `selection`, when given, narrows the run to the classes/methods an explicit
 * Test Explorer request asked for.
 */
export function buildStudioBootstrapScript(selection?: TestSelection, slow?: SlowTestFilter): string {
	return `--!strict
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run in Roblox
-- Studio" profile. Regenerated before every run -- nothing to edit here.

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local rbxtsInclude = ReplicatedStorage:FindFirstChild("rbxts_include")
if not rbxtsInclude then
	error("[lunit] ReplicatedStorage.rbxts_include not found -- the generated test place may have failed to build correctly")
end

local runtimeLibModule = rbxtsInclude:FindFirstChild("RuntimeLib")
if not runtimeLibModule then
	error("[lunit] ReplicatedStorage.rbxts_include.RuntimeLib not found -- the generated test place may have failed to build correctly")
end

-- RuntimeLib is hand-written (not roblox-ts compiled), so a plain require()
-- is safe here -- this is the one and only bare require() in this script.
local RuntimeLib = require(runtimeLibModule) :: any

local nodeModules = rbxtsInclude:FindFirstChild("node_modules")
if not nodeModules then
	error("[lunit] ReplicatedStorage.rbxts_include.node_modules not found -- the generated test place may have failed to build correctly")
end

local rbxtsScope = nodeModules:FindFirstChild("@rbxts")
if not rbxtsScope then
	error("[lunit] ReplicatedStorage.rbxts_include.node_modules[\\"@rbxts\\"] not found -- the generated test place may have failed to build correctly")
end

local lunitPackage = rbxtsScope:FindFirstChild("lunit")
if not lunitPackage then
	error("[lunit] could not find the @rbxts/lunit package in the synced node_modules -- is it installed?")
end
local lunitInit = lunitPackage:FindFirstChild("out")
if not lunitInit then
	error("[lunit] @rbxts/lunit's compiled \\"out\\" entrypoint was not found")
end
local lunit = RuntimeLib.import(rbxtsScope, lunitInit) :: any

${buildLuauEmitHelpers()}

${buildLuauTestFilterHelpers('Lune', selection, slow)}

local function isTestModule(name)
	return name:match("%.test$") ~= nil or name:match("%.spec$") ~= nil
end

local modules = {}
for _, instance in game:GetDescendants() do
	if
		instance:IsA("ModuleScript")
		and isTestModule(instance.Name)
		and (instance.Parent == nil or instance.Parent.Name ~= "forks")
	then
		table.insert(modules, instance)
	end
end

if #modules == 0 then
	warn("[lunit] no test modules found anywhere in the built place")
	return
end

local anyFailed = false
local classesLeftOut, testsLeftOut, slowLeftOut = 0, 0, 0

for _, moduleScript in modules do
	-- A class-level @Tag("Lune") module is never loaded when its source is
	-- readable; otherwise the loaded class's metadata decides.
	local sourceOk, source = pcall(function()
		return (moduleScript :: any).Source
	end)
	if sourceOk and lunitSourceHasClassTag(source) then
		classesLeftOut += 1
	else
		local loadOk, cls = pcall(RuntimeLib.import, rbxtsScope, moduleScript)
		if not loadOk then
			warn("failed to load test module \\"" .. moduleScript:GetFullName() .. "\\": " .. tostring(cls))
		elseif type(cls) == "table" then
			local className = tostring(cls)
			local run, classLeftOut, methodsLeftOut, slowMethodsLeftOut = lunitFilterClass(cls, className)
			if classLeftOut then
				classesLeftOut += 1
			end
			testsLeftOut += methodsLeftOut
			slowLeftOut += slowMethodsLeftOut
			if run then
				if lunitRunClass(lunit, cls, className) then
					anyFailed = true
				end
				lunitYieldBetweenClasses()
			end
		end
	end
end

if classesLeftOut > 0 or testsLeftOut > 0 then
	print("[lunit] left out " .. classesLeftOut .. " " .. LUNIT_EXCLUDED_TAG .. "-tagged test class(es) and "
		.. testsLeftOut .. " " .. LUNIT_EXCLUDED_TAG .. "-tagged test(s): run them with the Lune profile.")
end
if slowLeftOut > 0 then
	print("[lunit] " .. lunitSlowLeftOutNote(slowLeftOut))
end

if anyFailed then
	warn("[lunit] one or more tests failed")
end
`;
}
