import { buildLuauEmitHelpers } from './luauEmitHelpers';

/**
 * Builds the Roblox Studio bootstrap script for the "Run in Roblox Studio"
 * profile, run via Studio's `--task RunScript` CLI flag against the place
 * built from studioProjectTemplate.ts's generated Rojo project. Fully
 * generated and regenerated before every run -- nothing here is meant to be
 * hand-edited (there are no more per-project TODOs, unlike an earlier
 * version of this file: paths are now fully determined by the generated
 * Rojo project, not guessed).
 *
 * The one subtlety worth documenting: roblox-ts compiled modules start with
 * `local TS = _G[script]`, which is only populated by `TS.import`/
 * `TS.getModule` as a side effect of loading a module *through* them -- a
 * bare `require()` on a roblox-ts-compiled ModuleScript leaves `_G[script]`
 * nil and crashes on that very first line. So this script bootstraps the
 * chain by `require()`-ing only the one hand-written, non-compiled module
 * (`RuntimeLib`, shipped verbatim by roblox-ts) directly, then uses
 * `RuntimeLib.import`/`RuntimeLib.getModule` for everything else -- exactly
 * mirroring what compiled code itself does -- rather than calling `require()`
 * directly on Lunit or any test module.
 */
export function buildStudioBootstrapScript(packageScope: string, packageName: string): string {
	return `--!strict
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run in Roblox
-- Studio" profile. Regenerated before every run -- nothing to edit here.

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local rbxtsInclude = ReplicatedStorage:FindFirstChild("rbxts_include")
if not rbxtsInclude then
	error("[lunit] ReplicatedStorage.rbxts_include not found -- the generated test place may have failed to build correctly")
end

local runtimeLibModule = rbxtsInclude:FindFirstChild("RuntimeLib")
if not runtimeLibModule then
	error("[lunit] ReplicatedStorage.rbxts_include.RuntimeLib not found -- the generated test place may have failed to build correctly")
end

-- RuntimeLib is hand-written (not roblox-ts compiled), so a plain require()
-- is safe here -- this is the one and only bare require() in this script.
local RuntimeLib = require(runtimeLibModule) :: any

local nodeModules = rbxtsInclude:FindFirstChild("node_modules")
if not nodeModules then
	error("[lunit] ReplicatedStorage.rbxts_include.node_modules not found -- the generated test place may have failed to build correctly")
end

local rbxtsScope = nodeModules:FindFirstChild("@rbxts")
if not rbxtsScope then
	error("[lunit] ReplicatedStorage.rbxts_include.node_modules[\\"@rbxts\\"] not found -- the generated test place may have failed to build correctly")
end

local lunitPackage = rbxtsScope:FindFirstChild("lunit")
if not lunitPackage then
	error("[lunit] could not find the @rbxts/lunit package in the synced node_modules -- is it installed?")
end
local lunitInit = lunitPackage:FindFirstChild("out")
if not lunitInit then
	error("[lunit] @rbxts/lunit's compiled \\"out\\" entrypoint was not found")
end
local lunit = RuntimeLib.import(rbxtsScope, lunitInit) :: any

local packageScope = nodeModules:FindFirstChild("${packageScope}")
if not packageScope then
	error('[lunit] ReplicatedStorage.rbxts_include.node_modules["${packageScope}"] not found -- the generated test place may have failed to build correctly')
end
local packageUnderTest = packageScope:FindFirstChild("${packageName}")
if not packageUnderTest then
	error('[lunit] could not find "${packageName}" under the synced node_modules -- the generated test place may have failed to build correctly')
end

${buildLuauEmitHelpers()}

local function isTestModule(name)
	return name:match("%.test$") ~= nil or name:match("%.spec$") ~= nil
end

local function discoverModules(root, found)
	for _, child in root:GetDescendants() do
		if child:IsA("ModuleScript") and isTestModule(child.Name) then
			table.insert(found, child)
		end
	end
	return found
end

local modules = discoverModules(packageUnderTest, {})

if #modules == 0 then
	warn("[lunit] no test modules found under " .. packageUnderTest:GetFullName())
	return
end

local anyFailed = false

for _, moduleScript in modules do
	local loadOk, cls = pcall(RuntimeLib.import, rbxtsScope, moduleScript)
	if not loadOk then
		warn("failed to load test module \\"" .. moduleScript:GetFullName() .. "\\": " .. tostring(cls))
	elseif cls ~= nil then
		if lunitRunClass(lunit, cls, tostring(cls)) then
			anyFailed = true
		end
	end
end

if anyFailed then
	warn("[lunit] one or more tests failed")
end
`;
}
