import * as fs from 'fs';
import * as path from 'path';

export const CLI_LAUNCHER_FILE_NAME = 'lunit-cli.js';

/**
 * Writes (on every activation) a one-line launcher into the extension's
 * global storage directory that `require`s the currently installed
 * version's compiled cli.js. The point is a *stable* path: VS Code installs
 * each extension version into its own versioned folder
 * (`.../extensions/shadercloud.vscode-lunit-companion-0.1.3/`), so a command
 * baked into AGENTS.md pointing at `out/cli.js` directly would break on the
 * next update -- whereas `globalStorageUri` is keyed by extension id only
 * and survives upgrades. Rewriting it at activation is what keeps it
 * pointing at whichever version is actually running.
 *
 * Returns the launcher's absolute path, or undefined if it couldn't be
 * written (the CLI still works via `node <extension>/out/cli.js` directly).
 */
export function writeCliLauncher(
	globalStorageDir: string,
	extensionPath: string,
	log: (message: string) => void,
): string | undefined {
	const launcherPath = path.join(globalStorageDir, CLI_LAUNCHER_FILE_NAME);
	const cliPath = path.join(extensionPath, 'out', 'cli.js');
	const content = [
		'// Auto-generated by the Lunit Test Companion VS Code extension on every activation;',
		'// always points at the currently installed version. Do not edit.',
		`require(${JSON.stringify(cliPath)});`,
		'',
	].join('\n');
	try {
		fs.mkdirSync(globalStorageDir, { recursive: true });
		let existing: string | undefined;
		try {
			existing = fs.readFileSync(launcherPath, 'utf8');
		} catch {
			existing = undefined;
		}
		if (existing !== content) {
			fs.writeFileSync(launcherPath, content, 'utf8');
		}
		return launcherPath;
	} catch (err) {
		log(`[lunit] could not write the command-line launcher to ${launcherPath}: ${String(err)}`);
		return undefined;
	}
}
