import { buildLuauEmitHelpers } from './luauEmitHelpers';

/**
 * Builds the Luau job script sent to the companion Studio plugin
 * (studioPluginTemplate.ts) for the live-sync fast path: an already-open
 * Studio instance whose place is already being kept in sync by the
 * consuming project's own `rojo serve` + Rojo Studio plugin, so there's no
 * need to build a place or launch a new Studio process at all (see
 * liveSyncBridge.ts for how the extension detects this case).
 *
 * `loadstring`d and called directly by the plugin, so this returns its
 * result as a plain string (`LUNIT_OUTPUT_BUFFER`, see luauEmitHelpers.ts)
 * rather than printing to a file like the other two generated scripts.
 *
 * Discovery here can't assume any particular Rojo tree shape the way the
 * extension's own generated Studio place can (see studioProjectTemplate.ts):
 * this tree belongs entirely to the consuming project's own
 * default.project.json, which this extension has no say over and which, in
 * practice, doesn't necessarily mount the package under test at the name its
 * package.json would suggest (confirmed against a real dev workspace, where
 * a package's own folder name was used instead). So rather than navigating
 * an expected path, this does one `game:GetDescendants()` walk and picks out
 * a `RuntimeLib` ModuleScript, an `"@rbxts"` scope folder's `lunit` child,
 * and every `*.test` / `*.spec` ModuleScript by name, wherever they are --
 * except directly under a folder named `forks`, which excludes a real,
 * confirmed name collision: react-lua ports upstream React's own
 * "host config fork" convention verbatim (`forks/ReactFiberHostConfig.dom.lua`,
 * `.native.lua`, `.test.lua`, ...), so `@rbxts-js/ReactReconciler`'s `.test`
 * fork variant would otherwise be picked up as if it were a Lunit test file
 * and fail to load on its own (it isn't one) -- confirmed against a real
 * live-sync run, where it was caught and warned about gracefully (this
 * script already tolerates a candidate that fails to load) but was pure
 * noise, not a real problem to report.
 */
export function buildLiveSyncJobScript(): string {
	return `--!strict
-- AUTO-GENERATED by the Lunit VS Code extension's live-sync bridge. Sent to
-- the companion Studio plugin fresh for every run.

local runtimeLibModule = nil
local lunitModule = nil
local testModules = {}

for _, instance in game:GetDescendants() do
	if runtimeLibModule == nil and instance.Name == "RuntimeLib" and instance:IsA("ModuleScript") then
		runtimeLibModule = instance
	elseif
		lunitModule == nil
		and instance.Name == "lunit"
		and instance.Parent ~= nil
		and instance.Parent.Name == "@rbxts"
	then
		lunitModule = instance
	elseif
		instance:IsA("ModuleScript")
		and (instance.Name:match("%.test$") ~= nil or instance.Name:match("%.spec$") ~= nil)
		and (instance.Parent == nil or instance.Parent.Name ~= "forks")
	then
		table.insert(testModules, instance)
	end
end

if not runtimeLibModule then
	return "[lunit] could not find a \\"RuntimeLib\\" ModuleScript anywhere in this place -- is it a roblox-ts project synced via Rojo?"
end
if not lunitModule then
	return "[lunit] could not find an \\"@rbxts/lunit\\" package anywhere in this place -- is @rbxts/lunit installed and synced?"
end
if #testModules == 0 then
	return "[lunit] no *.test / *.spec ModuleScripts found anywhere in this place"
end

-- RuntimeLib is hand-written (not roblox-ts compiled), so a plain require()
-- is safe here -- this is the one and only bare require() in this script.
local RuntimeLib = require(runtimeLibModule) :: any
local lunit = RuntimeLib.import(runtimeLibModule, lunitModule:FindFirstChild("out") or lunitModule) :: any

${buildLuauEmitHelpers()}

for _, moduleScript in testModules do
	local loadOk, cls = pcall(RuntimeLib.import, runtimeLibModule, moduleScript)
	if not loadOk then
		warn("failed to load test module \\"" .. moduleScript:GetFullName() .. "\\": " .. tostring(cls))
	elseif cls ~= nil then
		lunitRunClass(lunit, cls, tostring(cls))
	end
end

return table.concat(LUNIT_OUTPUT_BUFFER, "\\n")
`;
}
