import { buildLuauBlockHelpers } from './luauBlockTemplate';
import { buildLuauEmitHelpers } from './luauEmitHelpers';
import { buildLuauTestFilterHelpers } from './luauTestFilterTemplate';

/**
 * Builds the Lune worker script used for roblox-ts `--type game` projects.
 *
 * The package runner (luneScriptTemplate.ts) discovers compiled `*.test.luau`
 * files on the filesystem and requires them by path, which works only because
 * a package's compiled output is entirely `script`-relative. A game project's
 * output resolves every import through the DataModel instead, so this runner
 * builds one from the project's Rojo file (rojoDataModelTemplate.ts), loads
 * the project's own `RuntimeLib` on top of it, and discovers tests by walking
 * that tree rather than the disk.
 *
 * It is driven by the extension in the same two modes as the package runner
 * (see luneBlockProtocol.ts), with the Rojo project first:
 *
 *   lune run lune-game-runner.luau <projectFile> --list
 *   lune run lune-game-runner.luau <projectFile> --job <jobFile>
 *
 * Modules are named by their DataModel full name (`ReplicatedStorage.Tests.
 * foo.test`), which is what a job refers to. Each worker process builds its
 * own DataModel and module cache: nothing is shared between blocks.
 *
 * Tag rules match the convention the roblox-ts community already uses with
 * Lunit, and which this profile needs in order to be usable at all: this
 * runtime has no engine, so a test that mounts React or touches a service
 * cannot run here. `@Tag("Studio")` marks those. A class-level `@Tag("Studio")`
 * is detected in the compiled *source*, before the module is ever required,
 * because such a module may legitimately touch the engine at load time; the
 * listing reports it as excluded and the planner never schedules it.
 * Method-level tags and the slow rule are applied by the planner from the
 * listed metadata.
 *
 * @param dataModelRequirePath Lune-style relative require path, from this
 *   script's own directory, to the generated `lune-rbx` module (no extension).
 */
export function buildLuneGameRunnerScript(dataModelRequirePath: string): string {
	return String.raw`--!nolint
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run with Lune"
-- profile (roblox-ts game project). Regenerated before every run -- edit
-- lunit.* settings instead of this file.

local fs = require("@lune/fs")
local process = require("@lune/process")

local rbx = require("` + dataModelRequirePath + String.raw`")

` + buildLuauEmitHelpers() + String.raw`

` + buildLuauBlockHelpers() + String.raw`

local projectFile = process.args[1]
local mode = process.args[2]
local jobFile = process.args[3]
if projectFile == nil or projectFile == "" then
	print("[lunit] ERROR: no Rojo project file was passed to the game runner.")
	process.exit(2)
end
if mode ~= "--list" and mode ~= "--job" then
	print("[lunit] ERROR: usage: lune run lune-game-runner.luau <projectFile> --list | --job <jobFile>")
	process.exit(2)
end

local function fail(text)
	print("[lunit] ERROR: " .. text)
end

--------------------------------------------------------------------------------
-- Tag rules: a class-level "Studio" tag in the compiled source keeps the
-- module from being loaded at all. See luauTestFilterTemplate.ts.
--------------------------------------------------------------------------------

` + buildLuauTestFilterHelpers('Studio') + String.raw`

--------------------------------------------------------------------------------
-- DataModel, runtime and discovery
--------------------------------------------------------------------------------

local loadedOk, dataModel = pcall(rbx.loadProject, projectFile)
if not loadedOk then
	fail('could not build a DataModel from "' .. projectFile .. '": ' .. tostring(dataModel))
	process.exit(2)
end
local game = dataModel.game

-- roblox-ts puts its runtime under rbxts_include, conventionally in
-- ReplicatedStorage. Fall back to a tree-wide search for projects that map it
-- somewhere else.
local include = game:GetService("ReplicatedStorage"):FindFirstChild("rbxts_include")
if include == nil then
	include = game:FindFirstChild("rbxts_include", true)
end
if include == nil then
	fail('no "rbxts_include" in the tree described by "' .. projectFile
		.. '". Compile the project first, and check that its Rojo project maps roblox-ts\'s include folder.')
	process.exit(2)
end

local runtimeOk, TS = pcall(function()
	return dataModel.require(include:WaitForChild("RuntimeLib"))
end)
if not runtimeOk then
	fail("could not load roblox-ts's RuntimeLib: " .. tostring(TS))
	process.exit(2)
end

local lunitOk, lunit = pcall(function()
	local scope = include:WaitForChild("node_modules"):WaitForChild("@rbxts")
	local package = scope:WaitForChild("lunit")
	-- Lunit reads _G[script], so it has to come through TS.import, which is
	-- what registers the runtime for it.
	if package:FindFirstChild("out") ~= nil then
		return TS.import(include, package, "out")
	end
	return TS.import(include, package)
end)
if not lunitOk then
	fail("could not load @rbxts/lunit through the DataModel: " .. tostring(lunit))
	process.exit(2)
end

local function isTestModule(instance)
	if instance.ClassName ~= "ModuleScript" then return false end
	local name = instance.Name
	return name:match("%.test$") ~= nil or name:match("%.spec$") ~= nil
end

-- Packages and the runtime are never test roots, and 'forks' mirrors the
-- exclusion the Studio live-sync profile already applies (React's host config
-- forks ship *.test modules that are not ours to run).
local function isExcludedLocation(instance)
	local current = instance
	while current ~= nil do
		local name = current.Name
		if name == "rbxts_include" or name == "node_modules" or name == "forks" then
			return true
		end
		current = current.Parent
	end
	return false
end

local modules = {}
local byName = {}
for _, descendant in game:GetDescendants() do
	if isTestModule(descendant) and not isExcludedLocation(descendant) then
		table.insert(modules, descendant)
		byName[descendant:GetFullName()] = descendant
	end
end
table.sort(modules, function(a, b)
	return a:GetFullName() < b:GetFullName()
end)

--------------------------------------------------------------------------------
-- --list: describe every loadable test class for the planner
--------------------------------------------------------------------------------

if mode == "--list" then
	local listing = { modules = {}, loadFailures = {}, excludedModules = {} }
	for _, module in modules do
		local fullName = module:GetFullName()
		local source = fs.readFile(dataModel.sourcePath(module))
		if lunitSourceHasClassTag(source) then
			-- Never even loaded: such a module may touch the engine at load time.
			table.insert(listing.excludedModules, fullName)
		else
			local ok, cls = pcall(dataModel.require, module)
			if not ok then
				fail("failed to load test module " .. fullName .. ": " .. tostring(cls))
				table.insert(listing.loadFailures, { path = fullName, error = tostring(cls) })
			elseif type(cls) ~= "table" then
				fail(fullName .. " must 'export =' its test class")
				table.insert(listing.loadFailures, { path = fullName, error = "the module did not return a test class (it must 'export =' the class)" })
			else
				table.insert(listing.modules, { path = fullName, class = lunitDescribeClass(cls, tostring(cls)) })
			end
		end
	end
	if #modules == 0 then
		print("No *.test / *.spec ModuleScripts found in the tree described by \"" .. projectFile .. "\".")
	end
	lunitEmitModules(listing)
	process.exit(0)
end

--------------------------------------------------------------------------------
-- --job: run one block in this VM
--------------------------------------------------------------------------------

local job = lunitReadJob(jobFile)
local failed, loadFailures, elapsedMs = lunitRunJob(job, function(fullName)
	local module = byName[fullName]
	if module == nil then
		error('no test module named "' .. tostring(fullName) .. '" in the tree described by "' .. projectFile .. '"', 0)
	end
	return dataModel.require(module)
end, lunit)
lunitEmitBlockSummary(job.block, failed, loadFailures, elapsedMs)
process.exit((failed > 0 or #loadFailures > 0) and 1 or 0)
`;
}
