import { buildLuauBlockHelpers } from './luauBlockTemplate';
import { buildLuauEmitHelpers } from './luauEmitHelpers';
import { buildLuauShim } from './luauShimTemplate';

/**
 * Builds the Lune worker script for the "Run with Lune" profile on a
 * roblox-ts package project. This is fully generated (never hand-edited) and
 * rewritten into a per-run directory before every run.
 *
 * It mirrors the discovery logic in @rbxts/lunit's own bundled
 * `scripts/lunit.luau` (walk `testsRoot` for `*.test.luau` / `*.spec.luau`,
 * `require` each via the `lune-shim` rbxRequire) but is driven by the
 * extension in two modes (see luneBlockProtocol.ts):
 *
 *   lune run lune-runner.luau <testsRoot> <lunitRoot> --list
 *   lune run lune-runner.luau <testsRoot> <lunitRoot> --job <jobFile>
 *
 * `--list` loads every discovered module once and prints each class's
 * compiled Lunit metadata, so the extension can plan which modules, methods
 * and @Each rows run in which worker process. `--job` runs one such block in
 * this VM: the job's modules in order, each narrowed to exactly the tests the
 * plan asked for (lifecycle hooks always kept), through the same
 * `lunitRunClass` loop every generated script uses, then a block summary.
 * Nothing else decides what runs: tag and slow rules are applied by the
 * planner from the listing, and a job naming a method the compiled class
 * lacks is reported as an error, never silently widened.
 *
 * Results are read via the `onTestEnd(label, result)` reporter hook, keeping
 * only the *last* callback per exact label before emitting. This was not the
 * first design tried: `TestRunResult.tests` (a `Map<ctor, TestClassRunResult>`)
 * looks like the "final, already-resolved" source of truth, but roblox-ts's
 * `Map.forEach`/`.get()` only work at call sites the TypeScript compiler
 * itself rewrites (they're compile-time macros, not real runtime methods) --
 * confirmed empirically by running this exact pattern against Lunit's own
 * compiled self-tests, where `:forEach()` fails from hand-written Luau even
 * called synchronously inside `reporter.getReport`. A plain function
 * callback like `onTestEnd` has no such restriction. The tradeoff: it fires
 * once per raw attempt, so for a plain `@Test` or `@Each` row (one attempt)
 * this is exact; for `@Retry` "keep the last call" is exactly Lunit's own
 * "stop as soon as it passes, otherwise last attempt" semantics; for
 * `@Repeat` (whose real rule is "any iteration failing fails it", not
 * "last wins") a test that fails then later passes can show as passed here
 * when Lunit would call it failed -- a narrow, documented gap for a rarely
 * combined decorator pair.
 *
 * Does NOT reuse @rbxts/lunit's own bundled `scripts/lune-shim.luau` -- see
 * luauShimTemplate.ts for why (in short: it doesn't implement `TS.getModule`,
 * so it crashes on the ordinary `import { X } from "@rbxts/lunit"` every
 * real test file uses). This inlines a fixed shim instead, requiring only
 * Lunit's own `promise.luau` from that same scripts directory.
 *
 * @param promiseRequirePath Relative (Lune-style `./`/`../`) require path,
 *   from the generated script's own directory, to
 *   `node_modules/@rbxts/lunit/scripts/promise` (no extension).
 */
export function buildLuneRunnerScript(promiseRequirePath: string): string {
	return `--!nolint
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run with Lune"
-- profile. Regenerated before every run -- edit lunit.* settings instead of
-- this file.

local process = require("@lune/process")

${buildLuauShim(promiseRequirePath)}

local fs = require("@lune/fs")

local testsRoot = process.args[1]
local lunitRoot = process.args[2]
local mode = process.args[3]
local jobFile = process.args[4]

${buildLuauEmitHelpers()}

${buildLuauBlockHelpers()}

local function isTestFile(name)
	return name:match("%.test%.luau$") ~= nil or name:match("%.spec%.luau$") ~= nil
end

local function discover(root, found)
	if not fs.isDir(root) then
		return found
	end
	for _, name in fs.readDir(root) do
		local path = root .. "/" .. name
		if fs.isDir(path) then
			if name ~= "node_modules" then
				discover(path, found)
			end
		elseif isTestFile(name) then
			table.insert(found, (path:gsub("%.luau$", "")))
		end
	end
	return found
end

if testsRoot == nil or lunitRoot == nil or (mode ~= "--list" and mode ~= "--job") then
	print("[lunit] ERROR: usage: lune run lune-runner.luau <testsRoot> <lunitRoot> --list | --job <jobFile>")
	process.exit(2)
end

local ok, lunit = pcall(rbxRequire, lunitRoot)
if not ok then
	print("Failed to load @rbxts/lunit from \\"" .. lunitRoot .. "\\": " .. tostring(lunit))
	print("Set \\"lunit.lunitRoot\\" if your compiled Lunit output lives somewhere else.")
	process.exit(2)
end

if mode == "--list" then
	local modulePaths = discover(testsRoot, {})
	table.sort(modulePaths)
	if #modulePaths == 0 then
		print("No tests found in \\"" .. testsRoot .. "\\". Set \\"lunit.testsRoot\\" if your compiled tests live somewhere else.")
	end
	local listing = { modules = {}, loadFailures = {}, excludedModules = {} }
	for _, modulePath in modulePaths do
		local loadOk, cls = pcall(rbxRequire, modulePath)
		if not loadOk then
			warn("failed to load test module \\"" .. modulePath .. "\\": " .. tostring(cls))
			table.insert(listing.loadFailures, { path = modulePath, error = tostring(cls) })
		elseif type(cls) ~= "table" then
			warn("test module \\"" .. modulePath .. "\\" did not return a test class")
			table.insert(listing.loadFailures, { path = modulePath, error = "the module did not return a test class (it must 'export =' the class)" })
		else
			table.insert(listing.modules, { path = modulePath, class = lunitDescribeClass(cls, tostring(cls)) })
		end
	end
	lunitEmitModules(listing)
	process.exit(0)
end

local job = lunitReadJob(jobFile)
local failed, loadFailures, elapsedMs = lunitRunJob(job, rbxRequire, lunit)
lunitEmitBlockSummary(job.block, failed, loadFailures, elapsedMs)
process.exit((failed > 0 or #loadFailures > 0) and 1 or 0)
`;
}
