import { buildLuauEmitHelpers } from './luauEmitHelpers';
import { buildLuauShim } from './luauShimTemplate';

/**
 * Builds the Lune entry script for the "Run with Lune" profile. This is
 * fully generated (never hand-edited) and rewritten before every run.
 *
 * It mirrors the discovery logic in @rbxts/lunit's own bundled
 * `scripts/lunit.luau` (walk `testsRoot` for `*.test.luau` / `*.spec.luau`,
 * `require` each via the `lune-shim` rbxRequire, run `lunit.TestRunner`)
 * but runs each discovered class through its own `TestRunner.fromClasses`
 * call instead of one shared runner, so each result can be attributed back to
 * its class unambiguously (nothing in Lunit's per-test data otherwise names
 * the owning class).
 *
 * Results are read via the `onTestEnd(label, result)` reporter hook, keeping
 * only the *last* callback per exact label before emitting. This was not the
 * first design tried: `TestRunResult.tests` (a `Map<ctor, TestClassRunResult>`)
 * looks like the "final, already-resolved" source of truth, but roblox-ts's
 * `Map.forEach`/`.get()` only work at call sites the TypeScript compiler
 * itself rewrites (they're compile-time macros, not real runtime methods) --
 * confirmed empirically by running this exact pattern against Lunit's own
 * compiled self-tests, where `:forEach()` fails from hand-written Luau even
 * called synchronously inside `reporter.getReport`. A plain function
 * callback like `onTestEnd` has no such restriction. The tradeoff: it fires
 * once per raw attempt, so for a plain `@Test` or `@Each` row (one attempt)
 * this is exact; for `@Retry` "keep the last call" is exactly Lunit's own
 * "stop as soon as it passes, otherwise last attempt" semantics; for
 * `@Repeat` (whose real rule is "any iteration failing fails it", not
 * "last wins") a test that fails then later passes can show as passed here
 * when Lunit would call it failed -- a narrow, documented gap for a rarely
 * combined decorator pair.
 *
 * Does NOT reuse @rbxts/lunit's own bundled `scripts/lune-shim.luau` -- see
 * luauShimTemplate.ts for why (in short: it doesn't implement `TS.getModule`,
 * so it crashes on the ordinary `import { X } from "@rbxts/lunit"` every
 * real test file uses). This inlines a fixed shim instead, requiring only
 * Lunit's own `promise.luau` from that same scripts directory.
 *
 * @param promiseRequirePath Relative (Lune-style `./`/`../`) require path,
 *   from the generated script's own directory, to
 *   `node_modules/@rbxts/lunit/scripts/promise` (no extension).
 */
export function buildLuneRunnerScript(promiseRequirePath: string): string {
	return `--!strict
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run with Lune"
-- profile. Regenerated before every run -- edit lunit.* settings instead of
-- this file.

local process = require("@lune/process")

${buildLuauShim(promiseRequirePath)}

local fs = require("@lune/fs")

local testsRoot = process.args[1] or "out/tests"
local lunitRoot = process.args[2] or "out"

${buildLuauEmitHelpers()}

local function isTestFile(name)
	return name:match("%.test%.luau$") ~= nil or name:match("%.spec%.luau$") ~= nil
end

local function discover(root, found)
	if not fs.isDir(root) then
		return found
	end
	for _, name in fs.readDir(root) do
		local path = root .. "/" .. name
		if fs.isDir(path) then
			if name ~= "node_modules" then
				discover(path, found)
			end
		elseif isTestFile(name) then
			table.insert(found, (path:gsub("%.luau$", "")))
		end
	end
	return found
end

local ok, lunit = pcall(rbxRequire, lunitRoot)
if not ok then
	print("Failed to load @rbxts/lunit from \\"" .. lunitRoot .. "\\": " .. tostring(lunit))
	print("Set \\"lunit.lunitRoot\\" if your compiled Lunit output lives somewhere else.")
	process.exit(1)
end

local modulePaths = discover(testsRoot, {})
if #modulePaths == 0 then
	print("No tests found in \\"" .. testsRoot .. "\\". Set \\"lunit.testsRoot\\" if your compiled tests live somewhere else.")
	process.exit(1)
end

local anyFailed = false

for _, modulePath in ipairs(modulePaths) do
	local loadOk, cls = pcall(rbxRequire, modulePath)
	if not loadOk then
		warn("failed to load test module \\"" .. modulePath .. "\\": " .. tostring(cls))
	elseif cls ~= nil then
		if lunitRunClass(lunit, cls, tostring(cls)) then
			anyFailed = true
		end
	end
end

process.exit(anyFailed and 1 or 0)
`;
}
