import { buildLuauEmitHelpers } from './luauEmitHelpers';
import { buildLuauTestFilterHelpers, SlowTestFilter } from './luauTestFilterTemplate';

/**
 * Builds the Lune entry script used for roblox-ts `--type game` projects.
 *
 * The package profile (luneScriptTemplate.ts) discovers compiled `*.test.luau`
 * files on the filesystem and requires them by path, which works only because
 * a package's compiled output is entirely `script`-relative. A game project's
 * output resolves every import through the DataModel instead, so this runner
 * builds one from the project's Rojo file (rojoDataModelTemplate.ts), loads
 * the project's own `RuntimeLib` on top of it, and discovers tests by walking
 * that tree rather than the disk.
 *
 * Results are emitted through the same `lunitRunClass` helper all the other
 * generated scripts use, so the Test Explorer parses a game run exactly as it
 * parses a package run.
 *
 * Tag rules match the convention the roblox-ts community already uses with
 * Lunit, and which this profile needs in order to be usable at all: this
 * runtime has no engine, so a test that mounts React or touches a service
 * cannot run here. `@Tag("Studio")` marks those. A class-level `@Tag("Studio")`
 * is detected in the compiled *source*, before the module is ever required,
 * because such a module may legitimately touch the engine at load time.
 *
 * Tests carrying one of `slow.tags` are left out too, unless `slow.allowed`
 * names them (see luauTestFilterTemplate.ts); "Run with Lune (Full)" passes no
 * slow filter.
 *
 * @param dataModelRequirePath Lune-style relative require path, from this
 *   script's own directory, to the generated `lune-rbx` module (no extension).
 */
export function buildLuneGameRunnerScript(dataModelRequirePath: string, slow?: SlowTestFilter): string {
	return String.raw`--!nolint
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run with Lune"
-- profile (roblox-ts game project). Regenerated before every run -- edit
-- lunit.* settings instead of this file.

local fs = require("@lune/fs")
local process = require("@lune/process")
local stdio = require("@lune/stdio")

local rbx = require("` + dataModelRequirePath + String.raw`")

` + buildLuauEmitHelpers() + String.raw`

local projectFile = process.args[1]
if projectFile == nil or projectFile == "" then
	print("[lunit] ERROR: no Rojo project file was passed to the game runner.")
	process.exit(1)
end

local function note(text)
	stdio.ewrite(stdio.style("dim") .. text .. stdio.style("reset") .. "\n")
end

local function fail(text)
	print("[lunit] ERROR: " .. text)
end

--------------------------------------------------------------------------------
-- Tag rules: tests tagged "Studio" are left out and reported as such. See
-- luauTestFilterTemplate.ts.
--------------------------------------------------------------------------------

` + buildLuauTestFilterHelpers('Studio', undefined, slow) + String.raw`

local EXCLUDED_TAG = LUNIT_EXCLUDED_TAG

--------------------------------------------------------------------------------
-- DataModel, runtime and discovery
--------------------------------------------------------------------------------

local loadedOk, dataModel = pcall(rbx.loadProject, projectFile)
if not loadedOk then
	fail('could not build a DataModel from "' .. projectFile .. '": ' .. tostring(dataModel))
	process.exit(1)
end
local game = dataModel.game

-- roblox-ts puts its runtime under rbxts_include, conventionally in
-- ReplicatedStorage. Fall back to a tree-wide search for projects that map it
-- somewhere else.
local include = game:GetService("ReplicatedStorage"):FindFirstChild("rbxts_include")
if include == nil then
	include = game:FindFirstChild("rbxts_include", true)
end
if include == nil then
	fail('no "rbxts_include" in the tree described by "' .. projectFile
		.. '". Compile the project first, and check that its Rojo project maps roblox-ts\'s include folder.')
	process.exit(1)
end

local runtimeOk, TS = pcall(function()
	return dataModel.require(include:WaitForChild("RuntimeLib"))
end)
if not runtimeOk then
	fail("could not load roblox-ts's RuntimeLib: " .. tostring(TS))
	process.exit(1)
end

local lunitOk, lunit = pcall(function()
	local scope = include:WaitForChild("node_modules"):WaitForChild("@rbxts")
	local package = scope:WaitForChild("lunit")
	-- Lunit reads _G[script], so it has to come through TS.import, which is
	-- what registers the runtime for it.
	if package:FindFirstChild("out") ~= nil then
		return TS.import(include, package, "out")
	end
	return TS.import(include, package)
end)
if not lunitOk then
	fail("could not load @rbxts/lunit through the DataModel: " .. tostring(lunit))
	process.exit(1)
end

local function isTestModule(instance)
	if instance.ClassName ~= "ModuleScript" then return false end
	local name = instance.Name
	return name:match("%.test$") ~= nil or name:match("%.spec$") ~= nil
end

-- Packages and the runtime are never test roots, and 'forks' mirrors the
-- exclusion the Studio live-sync profile already applies (React's host config
-- forks ship *.test modules that are not ours to run).
local function isExcludedLocation(instance)
	local current = instance
	while current ~= nil do
		local name = current.Name
		if name == "rbxts_include" or name == "node_modules" or name == "forks" then
			return true
		end
		current = current.Parent
	end
	return false
end

local modules = {}
for _, descendant in game:GetDescendants() do
	if isTestModule(descendant) and not isExcludedLocation(descendant) then
		table.insert(modules, descendant)
	end
end
table.sort(modules, function(a, b)
	return a:GetFullName() < b:GetFullName()
end)

local filter = process.args[2]
if filter ~= nil and filter ~= "" then
	filter = string.lower(filter)
	local matched = {}
	for _, module in modules do
		if string.find(string.lower(module:GetFullName()), filter, 1, true) ~= nil then
			table.insert(matched, module)
		end
	end
	modules = matched
end

--------------------------------------------------------------------------------
-- Run
--------------------------------------------------------------------------------

local classes = {}
local loadFailures = 0
local skippedClasses = 0
local skippedTests = 0
local slowTests = 0

for _, module in modules do
	local fullName = module:GetFullName()
	local source = fs.readFile(dataModel.sourcePath(module))
	if lunitSourceHasClassTag(source) then
		-- Never even loaded: such a module may touch the engine at load time.
		skippedClasses += 1
	else
		local ok, cls = pcall(dataModel.require, module)
		if not ok then
			loadFailures += 1
			fail("failed to load test module " .. fullName .. ": " .. tostring(cls))
		elseif type(cls) ~= "table" then
			loadFailures += 1
			fail(fullName .. " must 'export =' its test class")
		else
			local run, classLeftOut, testsLeftOut, slowLeftOut = lunitFilterClass(cls, tostring(cls))
			if classLeftOut then
				skippedClasses += 1
			end
			skippedTests += testsLeftOut
			slowTests += slowLeftOut
			if run and lunitCountTests(cls) > 0 then
				table.insert(classes, { cls = cls, fullName = fullName })
			end
		end
	end
end

if #classes == 0 and loadFailures == 0 then
	if slowTests > 0 then
		-- Nothing failed: everything left to run was slow, and the run said so.
		note(lunitSlowLeftOutNote(slowTests))
		process.exit(0)
	elseif skippedClasses > 0 or skippedTests > 0 then
		print("Every discovered test is tagged \"" .. EXCLUDED_TAG .. "\"; run them with the Studio profile.")
	else
		print("No tests found in the tree described by \"" .. projectFile .. "\".")
		print("Set \"lunit.lune.projectFile\" if a different Rojo project describes your tests.")
	end
	process.exit(1)
end

local anyFailed = false
for _, entry in classes do
	if lunitRunClass(lunit, entry.cls, tostring(entry.cls)) then
		anyFailed = true
	end
end

if skippedClasses > 0 or skippedTests > 0 then
	note("Left out " .. skippedClasses .. " " .. EXCLUDED_TAG .. "-tagged test class(es) and "
		.. skippedTests .. " " .. EXCLUDED_TAG .. "-tagged test(s): run them with the Studio profile.")
end
if slowTests > 0 then
	note(lunitSlowLeftOutNote(slowTests))
end
if loadFailures > 0 then
	fail(loadFailures .. " test module(s) failed to load.")
end

process.exit((anyFailed or loadFailures > 0) and 1 or 0)
`;
}
