/**
 * Emits `lune-rbx.luau`: a minimal, read-only Roblox DataModel for Lune,
 * built from the project's Rojo project file.
 *
 * Why this exists: roblox-ts emits fundamentally different code for the two
 * project types. A `--type package` project can't know where it will be
 * installed, so every import it emits is `script`-relative -- which is why
 * the filesystem `rbxRequire` in luauShimTemplate.ts is enough for packages.
 * A `--type game` project *does* know, because the Rojo project file decides
 * that (say) `src/game/shared` becomes `ReplicatedStorage.Game`, so roblox-ts
 * emits absolute DataModel paths instead:
 *
 *   local TS = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib"))
 *   TS.import(script, game:GetService("ReplicatedStorage"), "Game", "constants")
 *
 * Every import in every module then resolves by walking the DataModel, so the
 * missing input is the Rojo project file and the missing runtime is a
 * DataModel. This rebuilds that tree from the same project file Studio syncs,
 * maps each node back to its file, and loads modules with `script`, `game`
 * and `require` pointing into the tree. The project's real
 * `include/RuntimeLib.lua` and `include/Promise.lua` then run unchanged on
 * top of it, so Lune executes the exact Luau Studio does -- deliberately not
 * a reimplementation of `TS.import`, whose behaviour is too easy to get
 * subtly wrong.
 *
 * Deliberately NOT an engine: there is no Instance constructor, no real
 * services, no scheduler beyond Lune's `task`, and no clocks. A test that
 * needs those belongs in the Studio profile behind `@Tag("Studio")`. Services
 * the project never mapped resolve to empty stubs rather than erroring, so a
 * module that merely references one at load time still loads.
 */
export function buildRojoDataModelModule(): string {
	return String.raw`--!nolint
-- AUTO-GENERATED by the Lunit VS Code extension for the "Run with Lune"
-- profile. Regenerated before every run -- edit lunit.* settings instead of
-- this file.

local fs = require("@lune/fs")
local luau = require("@lune/luau")
local roblox = require("@lune/roblox")
local serde = require("@lune/serde")
local stdio = require("@lune/stdio")
local task = require("@lune/task")

-- Datatypes from @lune/roblox, exposed as globals exactly as the engine does.
-- These are the real implementations, not stand-ins: Vector3 components are
-- float32, typeof(CFrame.new()) is "CFrame", Vector3int16 keeps integer
-- components, and the operators behave as they do in Studio.
local DATATYPE_NAMES = {
	"Axes", "BrickColor", "CFrame", "Color3", "ColorSequence", "ColorSequenceKeypoint",
	"Enum", "Faces", "Font", "NumberRange", "NumberSequence", "NumberSequenceKeypoint",
	"PhysicalProperties", "Ray", "Rect", "Region3", "Region3int16", "UDim", "UDim2",
	"Vector2", "Vector2int16", "Vector3", "Vector3int16",
}

local rbx = {}

local function warn(...)
	local parts = table.pack(...)
	for i = 1, parts.n do parts[i] = tostring(parts[i]) end
	stdio.ewrite(stdio.color("yellow") .. table.concat(parts, "\t", 1, parts.n) .. stdio.color("reset") .. "\n")
end
rbx.warn = warn

-- globIgnorePaths entries, as Lua patterns matched against project-relative paths.
local function globToPattern(glob)
	local pattern = glob:gsub("[%^%$%(%)%%%.%[%]%+%-%?]", "%%%0")
	pattern = pattern:gsub("%*%*/", "\0"):gsub("%*%*", "\1"):gsub("%*", "[^/]*")
	pattern = pattern:gsub("%z", ".-/?"):gsub("\1", ".*")
	return "^" .. pattern .. "$"
end

local function normalize(path)
	path = path:gsub("\\", "/"):gsub("/%./", "/"):gsub("^%./", "")
	local changed = true
	while changed do
		local replaced
		path, replaced = path:gsub("[^/%.][^/]*/%.%./", "", 1)
		changed = replaced > 0
	end
	return path
end

local function join(dir, name)
	if dir == "" or dir == "." then return name end
	return dir .. "/" .. name
end

local function dirname(path)
	return path:match("^(.*)/[^/]*$") or "."
end

-- Rojo's file -> instance rules. Binary and model formats are deliberately
-- absent: they carry no runnable code, so a test run has nothing to gain.
local function classifyFile(fileName)
	local base = fileName:match("^(.+)%.server%.luau?$")
	if base then return base, "Script" end
	base = fileName:match("^(.+)%.client%.luau?$")
	if base then return base, "LocalScript" end
	base = fileName:match("^(.+)%.luau?$")
	if base then return base, "ModuleScript" end
	-- A .meta.json only adds properties to its sibling; never its own instance.
	if fileName:match("^(.+)%.meta%.json$") then return nil, nil end
	if fileName:match("^(.+)%.model%.json$") or fileName:match("^(.+)%.rbxmx?$") then return nil, nil end
	base = fileName:match("^(.+)%.json$")
	if base then return base, "JsonModule" end
	base = fileName:match("^(.+)%.txt$")
	if base then return base, "StringValue" end
	return nil, nil
end

local INIT_FILES = {
	{ "init.luau", "ModuleScript" }, { "init.lua", "ModuleScript" },
	{ "init.server.luau", "Script" }, { "init.server.lua", "Script" },
	{ "init.client.luau", "LocalScript" }, { "init.client.lua", "LocalScript" },
}

--------------------------------------------------------------------------------
-- Instances
--------------------------------------------------------------------------------

local Instance = {}
local InstanceMeta = {}
local SCRIPT_CLASSES = { ModuleScript = true, Script = true, LocalScript = true }

function InstanceMeta.__index(self, key)
	if key == "Parent" then return rawget(self, "_parent") end
	local properties = rawget(self, "_properties")
	if properties ~= nil and properties[key] ~= nil then return properties[key] end
	local method = Instance[key]
	if method ~= nil then return method end
	local child = Instance.FindFirstChild(self, key)
	if child ~= nil then return child end
	error(tostring(key) .. " is not a valid member of " .. rawget(self, "ClassName")
		.. ' "' .. Instance.GetFullName(self) .. '"', 2)
end

function InstanceMeta.__tostring(self)
	return rawget(self, "Name")
end

local function newInstance(context, name, className, parent, source, dir)
	return setmetatable({
		Name = name, ClassName = className, _parent = parent, _source = source, _dir = dir,
		_context = context, _explicit = {}, _explicitOrder = {}, _properties = nil, _children = nil,
	}, InstanceMeta)
end

local function isIgnored(context, path)
	local relative = normalize(path)
	for _, pattern in context.ignore do
		if relative:match(pattern) then return true end
	end
	return false
end

local nodeFromDirectory
local nodeFromTree

local function nodeFromFile(context, name, path, parent)
	local base, className = classifyFile(path:match("[^/]+$"))
	if base == nil then return nil end
	return newInstance(context, name or base, className, parent, path, nil)
end

function nodeFromDirectory(context, name, path, parent, classNameOverride)
	local nestedProject = join(path, "default.project.json")
	if fs.isFile(nestedProject) then
		-- A $path directory may itself be a Rojo project; its own tree wins.
		return nodeFromTree(context, name, rbx.readProject(nestedProject).tree, parent, path)
	end
	for _, init in INIT_FILES do
		local initPath = join(path, init[1])
		if fs.isFile(initPath) then
			return newInstance(context, name, init[2], parent, initPath, path)
		end
	end
	return newInstance(context, name, classNameOverride or "Folder", parent, nil, path)
end

function nodeFromTree(context, name, tree, parent, baseDir)
	local node
	local path = tree["$path"]
	-- Rojo's { "optional": "path" } form: absent is fine, e.g. not compiled yet.
	if type(path) == "table" then path = path.optional end
	if path ~= nil then
		local resolved = normalize(join(baseDir, path))
		if fs.isDir(resolved) then
			node = nodeFromDirectory(context, name, resolved, parent, tree["$className"])
		elseif fs.isFile(resolved) then
			node = nodeFromFile(context, name, resolved, parent)
		end
	end
	if node == nil then
		node = newInstance(context, name, tree["$className"] or "Folder", parent, nil, nil)
	end
	local properties = tree["$properties"]
	if type(properties) == "table" then
		local applied = rawget(node, "_properties") or {}
		for key, value in properties do applied[key] = value end
		rawset(node, "_properties", applied)
	end
	for key, value in tree do
		if type(key) == "string" and key:sub(1, 1) ~= "$" then
			local child = nodeFromTree(context, key, value, node, baseDir)
			node._explicit[key] = child
			table.insert(node._explicitOrder, child)
		end
	end
	return node
end

local function loadChildren(self)
	local children = rawget(self, "_children")
	if children ~= nil then return children end
	children = { byName = {}, list = {} }
	local function add(child)
		if child ~= nil and children.byName[child.Name] == nil then
			children.byName[child.Name] = child
			table.insert(children.list, child)
		end
	end
	-- Children named by the project shadow same-named files on disk, as in Rojo.
	for _, child in rawget(self, "_explicitOrder") do add(child) end
	local dir = rawget(self, "_dir")
	local context = rawget(self, "_context")
	if dir ~= nil and fs.isDir(dir) then
		local entries = fs.readDir(dir)
		table.sort(entries)
		for _, entry in entries do
			local path = join(dir, entry)
			if not isIgnored(context, path) then
				if fs.isDir(path) then
					add(nodeFromDirectory(context, entry, path, self, nil))
				elseif not entry:match("^init%.") then
					add(nodeFromFile(context, nil, path, self))
				end
			end
		end
	end
	rawset(self, "_children", children)
	return children
end

function Instance.FindFirstChild(self, name, recursive)
	local children = loadChildren(self)
	local found = children.byName[name]
	if found ~= nil or not recursive then return found end
	for _, child in children.list do
		found = Instance.FindFirstChild(child, name, true)
		if found ~= nil then return found end
	end
	return nil
end

function Instance.WaitForChild(self, name)
	local child = Instance.FindFirstChild(self, name)
	if child == nil then
		-- Studio would block forever; headlessly the file simply is not there.
		error(name .. ' is not a child of "' .. Instance.GetFullName(self) .. '" (is the project compiled?)', 2)
	end
	return child
end

function Instance.GetChildren(self)
	return table.clone(loadChildren(self).list)
end

function Instance.GetDescendants(self)
	local result = {}
	local function walk(node)
		for _, child in loadChildren(node).list do
			table.insert(result, child)
			walk(child)
		end
	end
	walk(self)
	return result
end

function Instance.IsA(self, className)
	local own = rawget(self, "ClassName")
	return own == className
		or className == "Instance"
		or (className == "LuaSourceContainer" and SCRIPT_CLASSES[own] == true)
		or (className == "BaseScript" and (own == "Script" or own == "LocalScript"))
end

function Instance.FindFirstAncestorWhichIsA(self, className)
	local current = rawget(self, "_parent")
	while current ~= nil do
		if Instance.IsA(current, className) then return current end
		current = rawget(current, "_parent")
	end
	return nil
end

function Instance.FindFirstAncestor(self, name)
	local current = rawget(self, "_parent")
	while current ~= nil do
		if rawget(current, "Name") == name then return current end
		current = rawget(current, "_parent")
	end
	return nil
end

function Instance.IsDescendantOf(self, ancestor)
	local current = rawget(self, "_parent")
	while current ~= nil do
		if current == ancestor then return true end
		current = rawget(current, "_parent")
	end
	return false
end

function Instance.GetFullName(self)
	local names = {}
	local current = self
	while current ~= nil and rawget(current, "_parent") ~= nil do
		table.insert(names, 1, rawget(current, "Name"))
		current = rawget(current, "_parent")
	end
	return table.concat(names, ".")
end

function Instance.GetAttribute() return nil end
function Instance.GetAttributes() return {} end

function Instance.GetService(self, name)
	local service = Instance.FindFirstChild(self, name)
	if service ~= nil then return service end
	-- A service the project never mapped: an empty stub, so a module that only
	-- references it at load time still loads. Actually driving the engine
	-- through one is out of scope here -- tag such a test @Tag("Studio").
	local context = rawget(self, "_context")
	if context.services[name] == nil then
		context.services[name] = newInstance(context, name, name, self, nil, nil)
	end
	return context.services[name]
end

--------------------------------------------------------------------------------
-- Engine stubs: only what RuntimeLib and Promise need in order to load.
--------------------------------------------------------------------------------

local function makeHeartbeat()
	local signal = {}
	function signal.Connect(_, callback)
		local connection = { Connected = true }
		function connection.Disconnect() connection.Connected = false end
		task.spawn(function()
			while connection.Connected do
				local dt = task.wait()
				if connection.Connected then callback(dt) end
			end
		end)
		return connection
	end
	function signal.Wait() return task.wait() end
	return signal
end

local function makeRunService()
	local function no() return false end
	return {
		Name = "RunService", ClassName = "RunService", Heartbeat = makeHeartbeat(),
		IsStudio = no, IsRunning = no, IsClient = no, IsServer = no, IsEdit = no,
	}
end

--------------------------------------------------------------------------------
-- Projects and module loading
--------------------------------------------------------------------------------

function rbx.readProject(projectFile)
	return serde.decode("json", fs.readFile(projectFile))
end

-- Builds the DataModel described by projectFile and returns the handle the
-- generated runner uses: { game, require, isInstance, sourcePath, environmentFor }.
function rbx.loadProject(projectFile)
	local project = rbx.readProject(projectFile)
	if type(project) ~= "table" or type(project.tree) ~= "table" then
		error('"' .. projectFile .. '" is not a Rojo project file (it has no "tree")', 0)
	end
	local context = { ignore = {}, services = {} }
	for _, glob in project.globIgnorePaths or {} do
		table.insert(context.ignore, globToPattern(glob))
	end
	context.services.RunService = makeRunService()

	local game = nodeFromTree(context, "Game", project.tree, nil, dirname(projectFile))

	-- Scan the whole tree up front. Lune's fs calls yield, and a child lookup
	-- can happen inside __index (script.Parent.charm), where yielding is an
	-- error. The tree is a few hundred files, so eager loading costs little.
	local function preload(node)
		for _, child in loadChildren(node).list do preload(child) end
	end
	preload(game)

	local sharedG = {}
	local moduleCache = {}
	local loading = {}
	local datatypes = {}
	for _, name in DATATYPE_NAMES do datatypes[name] = roblox[name] end

	local requireModule

	-- Roblox's require-by-string, resolved inside the tree: "./x" is a sibling
	-- of the calling script, "../x" a sibling of its parent, "@self/x" its own
	-- child. Charm and several other packages rely on this form.
	local function resolveStringRequire(script, path)
		local segments = string.split(path, "/")
		local current
		local first = segments[1]
		if first == "@self" then
			current = script
		elseif first == "." then
			current = rawget(script, "_parent")
		elseif first == ".." then
			current = rawget(rawget(script, "_parent") or {}, "_parent")
		else
			error('unsupported require path "' .. path .. '" in ' .. Instance.GetFullName(script), 3)
		end
		for i = 2, #segments do
			local segment = segments[i]
			if current == nil then
				break
			elseif segment == ".." then
				current = rawget(current, "_parent")
			elseif segment ~= "." and segment ~= "" then
				current = Instance.FindFirstChild(current, segment)
			end
		end
		if current == nil then
			error('could not resolve require "' .. path .. '" from ' .. Instance.GetFullName(script), 3)
		end
		return current
	end

	local function environmentFor(script)
		local env = {
			script = script,
			game = game,
			workspace = Instance.FindFirstChild(game, "Workspace"),
			require = function(target)
				if type(target) == "string" then
					return requireModule(resolveStringRequire(script, target))
				end
				return requireModule(target)
			end,
			task = task,
			warn = warn,
			_G = sharedG,
			tick = os.clock,
		}
		for name, value in datatypes do env[name] = value end
		return env
	end

	function requireModule(module)
		if type(module) ~= "table" or getmetatable(module) ~= InstanceMeta then
			error("require expects a ModuleScript, got " .. typeof(module), 2)
		end
		local cached = moduleCache[module]
		if cached ~= nil then return cached.value end
		local className = rawget(module, "ClassName")
		local source = rawget(module, "_source")
		if source == nil or (className ~= "ModuleScript" and className ~= "JsonModule") then
			error("require expects a ModuleScript, got " .. tostring(className)
				.. ' "' .. Instance.GetFullName(module) .. '"', 2)
		end
		if className == "JsonModule" then
			local decoded = serde.decode("json", fs.readFile(source))
			moduleCache[module] = { value = decoded }
			return decoded
		end
		if loading[module] then
			error('circular require of "' .. Instance.GetFullName(module) .. '"', 2)
		end
		loading[module] = true
		local ok, value = pcall(function()
			-- The module's globals arrive as locals of the chunk, not through a
			-- custom environment: a custom environment switches off Luau's fast
			-- builtin calls (math, bit32, buffer...), which made compute-heavy
			-- tests run far slower than in Studio. The prelude shares the first
			-- line, so line numbers in errors stay right. These names count
			-- towards Luau's 200 locals per function, and a module assigning an
			-- undeclared global now writes Lune's shared globals.
			local names, values = {}, {}
			for name, value in environmentFor(module) do
				table.insert(names, name)
				table.insert(values, value)
			end
			local chunk = luau.load("local " .. table.concat(names, ", ") .. " = ...; " .. fs.readFile(source), {
				debugName = source,
			})
			return chunk(table.unpack(values, 1, #names))
		end)
		loading[module] = nil
		if not ok then
			-- Name each link, so a failure deep in a dependency reports the
			-- chain that reached it rather than only the leaf.
			error(Instance.GetFullName(module) .. ": " .. tostring(value), 0)
		end
		moduleCache[module] = { value = value }
		return value
	end

	return {
		game = game,
		require = requireModule,
		isInstance = function(value)
			return type(value) == "table" and getmetatable(value) == InstanceMeta
		end,
		-- The file a script instance was built from, or nil.
		sourcePath = function(instance)
			return rawget(instance, "_source")
		end,
		environmentFor = environmentFor,
	}
end

return rbx
`;
}
